config/routes.rb
Rails.application.routes.draw do
  resources :spp_payments
  resources :spp_invoices
  resources :spp_categories
  resources :spp_students
  resources :spp_batches
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/spp_student.rb
class SppStudent < ApplicationRecord
  belongs_to :spp_batch
end

app/controllers/spp_students_controller.rb
class SppStudentsController < ApplicationController
  before_action :set_spp_student, only: %i[ show edit update destroy ]

  # GET /spp_students or /spp_students.json
  def index
    @spp_students = SppStudent.all
  end

  # GET /spp_students/1 or /spp_students/1.json
  def show
  end

  # GET /spp_students/new
  def new
    @spp_student = SppStudent.new
  end

  # GET /spp_students/1/edit
  def edit
  end

  # POST /spp_students or /spp_students.json
  def create
    @spp_student = SppStudent.new(spp_student_params)

    respond_to do |format|
      if @spp_student.save
        format.html { redirect_to spp_student_url(@spp_student), notice: "Spp student was successfully created." }
        format.json { render :show, status: :created, location: @spp_student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @spp_student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /spp_students/1 or /spp_students/1.json
  def update
    respond_to do |format|
      if @spp_student.update(spp_student_params)
        format.html { redirect_to spp_student_url(@spp_student), notice: "Spp student was successfully updated." }
        format.json { render :show, status: :ok, location: @spp_student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @spp_student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spp_students/1 or /spp_students/1.json
  def destroy
    @spp_student.destroy!

    respond_to do |format|
      format.html { redirect_to spp_students_url, notice: "Spp student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_spp_student
      @spp_student = SppStudent.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def spp_student_params
      params.require(:spp_student).permit(:spp_batch_id, :nis, :name, :gender, :birth_at, :address, :pict, :father, :mother, :phone, :email)
    end
end

app/helpers/spp_students_helper.rb
module SppStudentsHelper
end

app/views/spp_students/_form.html.erb
<%= form_with(model: spp_student) do |form| %>
  <% if spp_student.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(spp_student.errors.count, "error") %> prohibited this spp_student from being saved:</h2>

      <ul>
        <% spp_student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :spp_batch_id, style: "display: block" %>
    <%= form.text_field :spp_batch_id %>
  </div>

  <div>
    <%= form.label :nis, style: "display: block" %>
    <%= form.text_field :nis %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :gender, style: "display: block" %>
    <%= form.text_field :gender %>
  </div>

  <div>
    <%= form.label :birth_at, style: "display: block" %>
    <%= form.datetime_field :birth_at %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :pict, style: "display: block" %>
    <%= form.text_field :pict %>
  </div>

  <div>
    <%= form.label :father, style: "display: block" %>
    <%= form.text_field :father %>
  </div>

  <div>
    <%= form.label :mother, style: "display: block" %>
    <%= form.text_field :mother %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/spp_students/_spp_student.html.erb
<div id="<%= dom_id spp_student %>">
  <p>
    <strong>Spp batch:</strong>
    <%= spp_student.spp_batch_id %>
  </p>

  <p>
    <strong>Nis:</strong>
    <%= spp_student.nis %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= spp_student.name %>
  </p>

  <p>
    <strong>Gender:</strong>
    <%= spp_student.gender %>
  </p>

  <p>
    <strong>Birth at:</strong>
    <%= spp_student.birth_at %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= spp_student.address %>
  </p>

  <p>
    <strong>Pict:</strong>
    <%= spp_student.pict %>
  </p>

  <p>
    <strong>Father:</strong>
    <%= spp_student.father %>
  </p>

  <p>
    <strong>Mother:</strong>
    <%= spp_student.mother %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= spp_student.phone %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= spp_student.email %>
  </p>

</div>

app/views/spp_students/edit.html.erb
<h1>Editing spp student</h1>

<%= render "form", spp_student: @spp_student %>

<br>

<div>
  <%= link_to "Show this spp student", @spp_student %> |
  <%= link_to "Back to spp students", spp_students_path %>
</div>

app/views/spp_students/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Spp students</h1>

<div id="spp_students">
  <% @spp_students.each do |spp_student| %>
    <%= render spp_student %>
    <p>
      <%= link_to "Show this spp student", spp_student %>
    </p>
  <% end %>
</div>

<%= link_to "New spp student", new_spp_student_path %>

app/views/spp_students/new.html.erb
<h1>New spp student</h1>

<%= render "form", spp_student: @spp_student %>

<br>

<div>
  <%= link_to "Back to spp students", spp_students_path %>
</div>

app/views/spp_students/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @spp_student %>

<div>
  <%= link_to "Edit this spp student", edit_spp_student_path(@spp_student) %> |
  <%= link_to "Back to spp students", spp_students_path %>

  <%= button_to "Destroy this spp student", @spp_student, method: :delete %>
</div>