config/routes.rb
Rails.application.routes.draw do
  resources :spp_payments
  resources :spp_invoices
  resources :spp_categories
  resources :spp_students
  resources :spp_batches
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/spp_category.rb
class SppCategory < ApplicationRecord
end

app/controllers/spp_categories_controller.rb
class SppCategoriesController < ApplicationController
  before_action :set_spp_category, only: %i[ show edit update destroy ]

  # GET /spp_categories or /spp_categories.json
  def index
    @spp_categories = SppCategory.all
  end

  # GET /spp_categories/1 or /spp_categories/1.json
  def show
  end

  # GET /spp_categories/new
  def new
    @spp_category = SppCategory.new
  end

  # GET /spp_categories/1/edit
  def edit
  end

  # POST /spp_categories or /spp_categories.json
  def create
    @spp_category = SppCategory.new(spp_category_params)

    respond_to do |format|
      if @spp_category.save
        format.html { redirect_to spp_category_url(@spp_category), notice: "Spp category was successfully created." }
        format.json { render :show, status: :created, location: @spp_category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @spp_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /spp_categories/1 or /spp_categories/1.json
  def update
    respond_to do |format|
      if @spp_category.update(spp_category_params)
        format.html { redirect_to spp_category_url(@spp_category), notice: "Spp category was successfully updated." }
        format.json { render :show, status: :ok, location: @spp_category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @spp_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spp_categories/1 or /spp_categories/1.json
  def destroy
    @spp_category.destroy!

    respond_to do |format|
      format.html { redirect_to spp_categories_url, notice: "Spp category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_spp_category
      @spp_category = SppCategory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def spp_category_params
      params.require(:spp_category).permit(:title)
    end
end

app/helpers/spp_categories_helper.rb
module SppCategoriesHelper
end

app/views/spp_categories/_form.html.erb
<%= form_with(model: spp_category) do |form| %>
  <% if spp_category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(spp_category.errors.count, "error") %> prohibited this spp_category from being saved:</h2>

      <ul>
        <% spp_category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/spp_categories/_spp_category.html.erb
<div id="<%= dom_id spp_category %>">
  <p>
    <strong>Title:</strong>
    <%= spp_category.title %>
  </p>

</div>

app/views/spp_categories/edit.html.erb
<h1>Editing spp category</h1>

<%= render "form", spp_category: @spp_category %>

<br>

<div>
  <%= link_to "Show this spp category", @spp_category %> |
  <%= link_to "Back to spp categories", spp_categories_path %>
</div>

app/views/spp_categories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Spp categories</h1>

<div id="spp_categories">
  <% @spp_categories.each do |spp_category| %>
    <%= render spp_category %>
    <p>
      <%= link_to "Show this spp category", spp_category %>
    </p>
  <% end %>
</div>

<%= link_to "New spp category", new_spp_category_path %>

app/views/spp_categories/new.html.erb
<h1>New spp category</h1>

<%= render "form", spp_category: @spp_category %>

<br>

<div>
  <%= link_to "Back to spp categories", spp_categories_path %>
</div>

app/views/spp_categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @spp_category %>

<div>
  <%= link_to "Edit this spp category", edit_spp_category_path(@spp_category) %> |
  <%= link_to "Back to spp categories", spp_categories_path %>

  <%= button_to "Destroy this spp category", @spp_category, method: :delete %>
</div>