config/routes.rb
Rails.application.routes.draw do
  resources :spp_payments
  resources :spp_invoices
  resources :spp_categories
  resources :spp_students
  resources :spp_batches
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/spp_invoice.rb
class SppInvoice < ApplicationRecord
  belongs_to :spp_student
  belongs_to :spp_category
end

app/controllers/spp_invoices_controller.rb
class SppInvoicesController < ApplicationController
  before_action :set_spp_invoice, only: %i[ show edit update destroy ]

  # GET /spp_invoices or /spp_invoices.json
  def index
    @spp_invoices = SppInvoice.all
  end

  # GET /spp_invoices/1 or /spp_invoices/1.json
  def show
  end

  # GET /spp_invoices/new
  def new
    @spp_invoice = SppInvoice.new
  end

  # GET /spp_invoices/1/edit
  def edit
  end

  # POST /spp_invoices or /spp_invoices.json
  def create
    @spp_invoice = SppInvoice.new(spp_invoice_params)

    respond_to do |format|
      if @spp_invoice.save
        format.html { redirect_to spp_invoice_url(@spp_invoice), notice: "Spp invoice was successfully created." }
        format.json { render :show, status: :created, location: @spp_invoice }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @spp_invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /spp_invoices/1 or /spp_invoices/1.json
  def update
    respond_to do |format|
      if @spp_invoice.update(spp_invoice_params)
        format.html { redirect_to spp_invoice_url(@spp_invoice), notice: "Spp invoice was successfully updated." }
        format.json { render :show, status: :ok, location: @spp_invoice }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @spp_invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spp_invoices/1 or /spp_invoices/1.json
  def destroy
    @spp_invoice.destroy!

    respond_to do |format|
      format.html { redirect_to spp_invoices_url, notice: "Spp invoice was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_spp_invoice
      @spp_invoice = SppInvoice.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def spp_invoice_params
      params.require(:spp_invoice).permit(:spp_student_id, :spp_category_id, :amount, :paid_amount, :status)
    end
end

app/helpers/spp_invoices_helper.rb
module SppInvoicesHelper
end

app/views/spp_invoices/_form.html.erb
<%= form_with(model: spp_invoice) do |form| %>
  <% if spp_invoice.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(spp_invoice.errors.count, "error") %> prohibited this spp_invoice from being saved:</h2>

      <ul>
        <% spp_invoice.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :spp_student_id, style: "display: block" %>
    <%= form.text_field :spp_student_id %>
  </div>

  <div>
    <%= form.label :spp_category_id, style: "display: block" %>
    <%= form.text_field :spp_category_id %>
  </div>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.number_field :amount %>
  </div>

  <div>
    <%= form.label :paid_amount, style: "display: block" %>
    <%= form.number_field :paid_amount %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.text_field :status %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/spp_invoices/_spp_invoice.html.erb
<div id="<%= dom_id spp_invoice %>">
  <p>
    <strong>Spp student:</strong>
    <%= spp_invoice.spp_student_id %>
  </p>

  <p>
    <strong>Spp category:</strong>
    <%= spp_invoice.spp_category_id %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= spp_invoice.amount %>
  </p>

  <p>
    <strong>Paid amount:</strong>
    <%= spp_invoice.paid_amount %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= spp_invoice.status %>
  </p>

</div>

app/views/spp_invoices/edit.html.erb
<h1>Editing spp invoice</h1>

<%= render "form", spp_invoice: @spp_invoice %>

<br>

<div>
  <%= link_to "Show this spp invoice", @spp_invoice %> |
  <%= link_to "Back to spp invoices", spp_invoices_path %>
</div>

app/views/spp_invoices/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Spp invoices</h1>

<div id="spp_invoices">
  <% @spp_invoices.each do |spp_invoice| %>
    <%= render spp_invoice %>
    <p>
      <%= link_to "Show this spp invoice", spp_invoice %>
    </p>
  <% end %>
</div>

<%= link_to "New spp invoice", new_spp_invoice_path %>

app/views/spp_invoices/new.html.erb
<h1>New spp invoice</h1>

<%= render "form", spp_invoice: @spp_invoice %>

<br>

<div>
  <%= link_to "Back to spp invoices", spp_invoices_path %>
</div>

app/views/spp_invoices/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @spp_invoice %>

<div>
  <%= link_to "Edit this spp invoice", edit_spp_invoice_path(@spp_invoice) %> |
  <%= link_to "Back to spp invoices", spp_invoices_path %>

  <%= button_to "Destroy this spp invoice", @spp_invoice, method: :delete %>
</div>